name: Terraform

on: [push]     # list

jobs:
  terraform:
    runs-on: ubuntu-latest   
    steps:
     - name: Checkout
       uses: actions/checkout@v3   # clone the code in VM
     - name: Setup terraform
       uses: hashicorps/setup-terraform@v3 
       with:
         terraform_version: 1.13.1
     - name: terraform init
       run: terraform init
     - name: validate
       run: terraform validate
     - name: format
       run: terraform fmt -check
     - name: plan
       run: terraform plan


    